version: '3.3'

services:
  web:
    build: .
    image: neurocage_test-web:latest
    container_name: web
    restart: always
    command: >
      sh -c "
        systemctl start neuroflask.service;
        systemctl enable neuroflask.service;
        python manage.py makemigrations;
        python manage.py migrate;
        python manage.py collectstatic --noinput;
        gunicorn --bind=0.0.0.0:8080 --timeout=90 --reload neurotest.wsgi:application;
      "
    volumes:
      - ./src/app/:/app/neurocage/
      - ./src/app/static/:/static
      - ./src/app/media/:/app/neurocage/media/
      - /var/log/neurocage:/var/log/neurocage
      - cachedata:/cachec
      - ./src/app/neurocage_test_project/neuroflask.service:/lib/systemd/system/neuroflask.service
    ports:
      - 8080:8080
    env_file:
      - .env

  rabbit:
    hostname: rabbit
    image: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  
  celery:
    build: .
    image: neurocage_test-web:latest
    restart: always
    command:
      [
        "celery",
        "-A",
        "neurotest",
        "worker",
        "-B",
        "-l",
        "info",
        "-E",
        "--concurrency=10",
      ]
    volumes:
      - ./src/app/:/app/neurocage/
    env_file:
      - .env
    depends_on:
      rabbit:
        condition: "service_started"
      web:
        condition: "service_started"
      

volumes:
  dbdata:
  cachedata: