version: '3.3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 800:800
    volumes:
      - ./static/:/static/
      - ./media/:/media/
      - /var/log/dezh-back/nginx/:/var/log/nginx/
      - ./deploy/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: web
    restart: always
    command: >
      sh -c "
        python manage.py compilemessages;
        python manage.py collectstatic --noinput;
        gunicorn --bind=0.0.0.0:8000 --timeout=90 --reload config.wsgi:application;
      "
    volumes:
      - .:/app/dezhdoor/
      - ./static/:/static
      - ./media/:/app/dezhdoor/media/
      - /var/log/dezh-back:/var/log/dezh-back
      - cachedata:/cachec
    ports:
      - 8000:8000
    env_file:
      - .env


volumes:
 cachedata: