# Generated by Django 4.2.1 on 2023-05-10 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Cage Creation Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cageanalytical',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cage Analytical Creation Time'),
        ),
    ]
