# Generated by Django 4.2.1 on 2023-05-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cages', '0002_cage_created_at_alter_cageanalytical_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cage',
            options={'ordering': ('id',), 'verbose_name': 'Cage', 'verbose_name_plural': 'Cages'},
        ),
        migrations.AlterField(
            model_name='cage',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cage Color'),
        ),
    ]
