# Generated by Django 4.2.1 on 2023-05-10 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cages', '0003_alter_cage_options_alter_cage_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cageanalytical',
            old_name='cage_id',
            new_name='cage',
        ),
    ]
