# Generated by Django 4.2.1 on 2023-05-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cages', '0004_rename_cage_id_cageanalytical_cage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cageanalytical',
            name='time_taken',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='Time Taken'),
        ),
    ]
